### PR TITLE
Upload schema as a release artifact

### PR DESCRIPTION
**Pull request by prescod**
CumulusCI now publishes a schema to the URL: https://github.com/SFDO-Tooling/CumulusCI/releases/latest/download/cumulusci.jsonschema.json

(not sure how to test this though)

### CODE REVIEW

**Review by jstvz — CHANGES_REQUESTED** [review]
This approach won't work, unfortunately.

The `actions/upload-artifact` action uploads an [artifact](https://docs.github.com/en/actions/advanced-guides/storing-workflow-data-as-artifacts), rather than a "release asset" (I misspoke and called it a "release artifact" in our slack thread). 

I suggest that we:
1. Create a workflow that  is triggered by the [release](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#webhook-events) event:
  ```yaml
on:
    release:
      - published
 ```
2. This workflow would then upload the json schema using one of the following actions:
  a. The unmaintained [actions/upload-release-asset](https://github.com/actions/upload-release-asset) action (👍🏾: easy, 👎🏾 : needs fork, 3PP, and SA).
  b. The third party [alexellis/upload-assets](https://github.com/alexellis/upload-assets) action (👍🏾: easy, 👎🏾 : needs fork, 3PP, and SA).
  c. Using [SFDO-Tooling/github-script](https://github.com/SFDO-Tooling/github-script) to create a release asset via [Ocktokit](https://octokit.github.io/rest.js/v18#repos-upload-release-asset) ➡️ [REST API](https://docs.github.com/en/rest/reference/repos#upload-a-release-asset)  (👍🏾: no fork/3PP, 👎🏾: code) 

Since this is a non-trivial amount of work I think it's okay to link directly to `main` if we want to go ahead and submit the schema to schema store while we figure out our approach.

**Comment by prescod** [comment]
I did notice the distinction but I was hoping (and still am) that release
artifacts might automatically become release assets after an actual release
happens?

This is how I came to believe (after running down a bunch of
upload-release-asset and API rabbit holes) that maybe it would "just work"?

The python-build-standalone project has tons of "Release Assets"[1] but I
only see workflows for uploading artifacts[2].

[1]
https://github.com/indygreg/python-build-standalone/releases/tag/20211017
[2]
https://github.com/indygreg/python-build-standalone/blob/main/.github/workflows/

By the way, the guy who "killed" actions/upload-release-asset (Andy McKay)
is an acquaintance of mine from Vancouver/ActiveState. Also a Plone/Zope
guy at one point so others on our team might know him.

**Comment by jstvz** [comment]
> The python-build-standalone project has tons of "Release Assets" but I only see workflows for uploading artifacts

Based on this [commit](https://github.com/indygreg/python-build-standalone/commit/2197ea176f9fef968998733976013900548c1e7a), it looks like uploading release artifacts is handled by a Rust CLI tool.

> By the way, the guy who "killed" actions/upload-release-asset (Andy McKay) is an acquaintance of mine from Vancouver/ActiveState. Also a Plone/Zope guy at one point so others on our team might know him.

Small world. I gotta get out of the house more. 😏

**Comment by jstvz** [comment]
>    c. Using [SFDO-Tooling/github-script](https://github.com/SFDO-Tooling/github-script) to create a release asset via [Ocktokit](https://octokit.github.io/rest.js/v18#repos-upload-release-asset) ➡️ [REST API](https://docs.github.com/en/rest/reference/repos#upload-a-release-asset)  (👍🏾: no fork/3PP, 👎🏾: code)

Probably the way to go, and wouldn't need octokit:
```console
❯ gh release upload --help
Upload asset files to a GitHub Release.

To define a display label for an asset, append text starting with '#' after the
file name.


USAGE
  gh release upload <tag> <files>... [flags]

FLAGS
  --clobber   Overwrite existing assets of the same name
```

**Pull request closed without merging**
