### PR TITLE
Feature/add collision-check option to  deploy task

### PR DESCRIPTION
**Pull request by jain-naman-sf**
Hey @jkasturi-sf Raising it for review.

### CODE REVIEW

**Comment by jain-naman-sf** [comment]
Hey @jkasturi-sf We have added a new option collision_check for Deploy Task. Added Tests as well.
Please review it.

**Review by jkasturi-sf — APPROVED** [review]
Good work @jain-naman-sf

**Comment by jain-naman-sf** [comment]
Hey @jkasturi-sf Removed that table header. Please approve it once again

**Review by jkasturi-sf — APPROVED** [review]
This looks good

**Pull request merged**
