### PR TITLE
Allowed namespace injection without managed

### PR DESCRIPTION
**Pull request by jain-naman-sf**

### CODE REVIEW

**Comment by lakshmi2506** [comment]
Hi @jkasturi-sf 

I have added the error message for the parse_url_string when the url doesn't have set origin. This is possible while we run flows.

Please review the code
Thank you

**Comment by jain-naman-sf** [comment]
Hey @jkasturi-sf Please review this PR

**Review by jstvz — CHANGES_REQUESTED** [review]
Thanks for your work here. I noticed two things we need to check:

1. Your changes look at the task options (managed and namespace) to decide about the namespace filter. But, the work item and discussion in #3089 suggests we should look at the details of the target org instead (e.g. [`self.org_config.namespace`](https://github.com/SFDO-Tooling/CumulusCI/blob/520b51128c7702a374da9a8838f38890082fd3de/cumulusci/core/config/org_config.py#L240)).
2. You don't have any tests that confirm the new behavior as specified in the acceptance criteria on the story.

So, we need the task to look at the target org's details to choose if the namespace filter is used, not just the task options.

Can you adjust this? Let me know if you need more information or if anything is unclear.

**Comment by jain-naman-sf** [comment]
Hey @jstvz I have added the functionality to infer namespace from target org directly along with tests.

**Review by jkasturi-sf — APPROVED** [review]
Looks good

**Review by jstvz — APPROVED** [review]

**Pull request merged**
