### PR TITLE
Feature/push api coverage

### PR DESCRIPTION
**Pull request by jofsky**
# Critical Changes

# Changes

# Issues Closed

### CODE REVIEW

**Comment by jstvz** [comment]
@jofsky What would you say to pairing on this Monday?

**Comment by jofsky** [comment]
@jstvz I'd love that! Thanks a ton!

**Comment by davisagli** [comment]
@jstvz @jofsky so based on the comments in standup today, it sounds like there is a new branch which should replace this pull request?

**Comment by jofsky** [comment]
@davisagli  yes I'll close this out

**Pull request closed without merging**
