### PR TITLE
Fix integration test errors

### PR DESCRIPTION
**Pull request by prescod**

### CODE REVIEW

**Review by prescod — COMMENTED** [review]
Test.

**Review by prescod — COMMENTED** [review]
Test

**Review by prescod — COMMENTED** [review]
Test

**Comment by prescod** [comment]
I didn't change this branch between the red "X" and the green checkmark. I just must merged main. So I think it properly detected that there was a point in the past when main wasn't installable and now it is installable.

**Review by jstvz — APPROVED** [review]

**Pull request merged**
