### PR TITLE
@W-17427085: Set ANNOY related dependencies to be optional

### PR DESCRIPTION
**Pull request by aditya-balachander**
Changes:
 - Remove `"annoy", "numpy", "pandas", "scikit-learn"` from dependencies under `pyproject.toml` and add them under optional dependencies
 - Created flag `OPTIONAL_DEPENDENCIES_AVAILABLE`, to indicate if ANNOY related dependencies are present in `select_utils.py`. If these optional dependencies are not available, for high volume of records (i.e. `complexity_constant >= 1000`), still Levenshtein Distance based selection will apply.
 - Skipped those pytests which have dependencies on `pandas` and ANNOY related optional dependencies under `test_select_utils.py`
 - Adding a warning message for non-zero similarity score when using ANNOY (for high volume of records). Updated the docs as well
 - Added additional workflow to run all unit tests with all optional dependencies installed

### CODE REVIEW

**Review by mjawadtp — DISMISSED** [review]
Looks good to me

**Review by jstvz — COMMENTED** [review]
Thanks for the updates, @aditya-balachander. The changes to make the optional dependencies conditional look good, but I recommend adding a new CI build that installs and tests with all optional dependencies (`select`). This will:

- Make sure everything works when optional dependencies are installed together.
- Catch compatibility issues early.

You can use the `uv sync --all-extras` command to install all optional dependencies. Let me know if you need help configuring the CI build to include this.

**Comment by aditya-balachander** [comment]
Hey @jstvz,

Have added the additional workflow. Let me know if this looks good

**Review by lakshmi2506 — APPROVED** [review]
LGTM

**Review by mjawadtp — APPROVED** [review]
Looks good to me

**Review by jstvz — APPROVED** [review]

**Pull request merged**
