### PR TITLE
Update BaseProjConf to use github3.repo.{file,directory}_contents

### PR DESCRIPTION
**Pull request by jstvz**
# Critical Changes

# Changes
* Oops, an update in CumulusCI 2.2.0 ended up breaking the update_dependencies task! Now fixed.

# Issues Closed

### CODE REVIEW

**Comment by davisagli** [comment]
I tested this by running dev_org for Cumulus and it's not working yet:

```
2018-11-21 20:08:12: Running task: update_dependencies
2018-11-21 20:08:12: Beginning task: UpdateDependencies
2018-11-21 20:08:12: 
2018-11-21 20:08:12: Preparing static dependencies map
2018-11-21 20:08:12: Processing dependencies from Github repo https://github.com/SalesforceFoundation/Households
2018-11-21 20:08:13: Task failed: update_dependencies
2018-11-21 20:08:13: Failing flow due to exception in task
Traceback (most recent call last):
  File "/Users/davisagli/Work/CumulusCI/cumulusci/core/flows.py", line 294, in _run_task
    task()
  File "/Users/davisagli/Work/CumulusCI/cumulusci/core/tasks.py", line 137, in __call__
    self.result = self._run_task()
  File "/Users/davisagli/Work/CumulusCI/cumulusci/tasks/salesforce/UpdateDependencies.py", line 72, in _run_task
    self.options["dependencies"], include_beta=self.options["include_beta"]
  File "/Users/davisagli/Work/CumulusCI/cumulusci/core/config/BaseProjectConfig.py", line 494, in get_static_dependencies
    dependency, include_beta=include_beta
  File "/Users/davisagli/Work/CumulusCI/cumulusci/core/config/BaseProjectConfig.py", line 567, in process_github_dependency
    contents = repo.directory_contents("unpackaged/pre", return_as=dict, **kwargs)
  File "/Users/davisagli/.pyenv/versions/3.6.5/envs/cci-dev-py36/lib/python3.6/site-packages/github3/repos/repo.py", line 1205, in directory_contents
    json = self._json(self._get(url, params={'ref': ref}), 200) or []
  File "/Users/davisagli/.pyenv/versions/3.6.5/envs/cci-dev-py36/lib/python3.6/site-packages/github3/models.py", line 156, in _json
    raise exceptions.error_for(response)
github3.exceptions.NotFoundError: 404 Not Found
Traceback (most recent call last):
  File "/Users/davisagli/.pyenv/versions/cci-dev-py36/bin/cci", line 11, in <module>
    load_entry_point('cumulusci', 'console_scripts', 'cci')()
  File "/Users/davisagli/.pyenv/versions/3.6.5/envs/cci-dev-py36/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/davisagli/.pyenv/versions/3.6.5/envs/cci-dev-py36/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/davisagli/.pyenv/versions/3.6.5/envs/cci-dev-py36/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/davisagli/.pyenv/versions/3.6.5/envs/cci-dev-py36/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/davisagli/.pyenv/versions/3.6.5/envs/cci-dev-py36/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/davisagli/.pyenv/versions/3.6.5/envs/cci-dev-py36/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/davisagli/Work/CumulusCI/cumulusci/cli/cci.py", line 213, in new_func
    func(config, *args, **kw)
  File "/Users/davisagli/Work/CumulusCI/cumulusci/cli/cci.py", line 1160, in flow_run
    handle_exception_debug(config, debug, no_prompt=no_prompt)
  File "/Users/davisagli/Work/CumulusCI/cumulusci/cli/cci.py", line 1152, in flow_run
    flow()
  File "/Users/davisagli/Work/CumulusCI/cumulusci/core/flows.py", line 214, in __call__
    self._run_step(stepnum, step_config)
  File "/Users/davisagli/Work/CumulusCI/cumulusci/core/flows.py", line 241, in _run_step
    self._run_flow(stepnum, step_config)
  File "/Users/davisagli/Work/CumulusCI/cumulusci/core/flows.py", line 269, in _run_flow
    flow()
  File "/Users/davisagli/Work/CumulusCI/cumulusci/core/flows.py", line 214, in __call__
    self._run_step(stepnum, step_config)
  File "/Users/davisagli/Work/CumulusCI/cumulusci/core/flows.py", line 243, in _run_step
    self._run_task(stepnum, step_config)
  File "/Users/davisagli/Work/CumulusCI/cumulusci/core/flows.py", line 305, in _run_task
    raise e
  File "/Users/davisagli/Work/CumulusCI/cumulusci/core/flows.py", line 294, in _run_task
    task()
  File "/Users/davisagli/Work/CumulusCI/cumulusci/core/tasks.py", line 137, in __call__
    self.result = self._run_task()
  File "/Users/davisagli/Work/CumulusCI/cumulusci/tasks/salesforce/UpdateDependencies.py", line 72, in _run_task
    self.options["dependencies"], include_beta=self.options["include_beta"]
  File "/Users/davisagli/Work/CumulusCI/cumulusci/core/config/BaseProjectConfig.py", line 494, in get_static_dependencies
    dependency, include_beta=include_beta
  File "/Users/davisagli/Work/CumulusCI/cumulusci/core/config/BaseProjectConfig.py", line 567, in process_github_dependency
    contents = repo.directory_contents("unpackaged/pre", return_as=dict, **kwargs)
  File "/Users/davisagli/.pyenv/versions/3.6.5/envs/cci-dev-py36/lib/python3.6/site-packages/github3/repos/repo.py", line 1205, in directory_contents
    json = self._json(self._get(url, params={'ref': ref}), 200) or []
  File "/Users/davisagli/.pyenv/versions/3.6.5/envs/cci-dev-py36/lib/python3.6/site-packages/github3/models.py", line 156, in _json
    raise exceptions.error_for(response)
github3.exceptions.NotFoundError: 404 Not Found
```

**Comment by davisagli** [comment]
https://api.github.com/repos/SalesforceFoundation/Households/contents/unpackaged/pre is the URL it was trying to load there

**Comment by jstvz** [comment]
Yup, just reproduced it.

**Comment by jstvz** [comment]
0.9.6: 

``` python
    def _json(self, response, status_code):
        ret = None
        if self._boolean(response, status_code, 404) and response.content:
            __logs__.info('Attempting to get JSON information from a Response '
                          'with status code %d expecting %d',
                          response.status_code, status_code)
            ret = response.json()
            headers = response.headers
            if ((headers.get('Last-Modified') or headers.get('ETag')) and
                    isinstance(ret, dict)):
                ret['Last-Modified'] = response.headers.get(
                    'Last-Modified', ''
                )
                ret['ETag'] = response.headers.get('ETag', '')
        __logs__.info('JSON was %sreturned', 'not ' if ret is None else '')
        return ret
```

1.2.0:

``` python
    def _json(self, response, expected_status_code, include_cache_info=True):
        ret = None
        if response is None:
            return None

        actual_status_code = response.status_code
        if actual_status_code != expected_status_code:
            if actual_status_code >= 400:
                raise exceptions.error_for(response)

            if actual_status_code == 304:
                # Received a response from someone passing in `etag=`
                return None

            LOG.warning('Expected status_code %d but got %d',
                        expected_status_code,
                        actual_status_code)

        try:
            ret = response.json()
        except ValueError:
            raise exceptions.UnexpectedResponse(response)

```

**Comment by jstvz** [comment]
We should probably refactor this soon, but I'm not a very good boy scout today. Works for me against Cumulus.

**Comment by davisagli** [comment]
Yep, working for me now. And I noticed that difference in handling 404 responses in some other places that I updated. Thanks for working on this.

**Pull request merged**
