### PR TITLE
Add IP Ranges Metadata ETL task

### PR DESCRIPTION
**Pull request by davidmreed**
# Critical Changes

# Changes

- We added the `add_profile_ip_ranges` Metadata ETL task.

# Issues Closed

### CODE REVIEW

**Review by prescod — APPROVED** [review]
Elegant uses of Pydantic!

You're sure that Salesforce supports IPV6-based filtering?

**Comment by davidmreed** [comment]
@prescod Great question, I don't know. Will test.

**Comment by davidmreed** [comment]
Yes, IPv6 login ranges do work.

I also replaced the inefficient way I was getting a network's end address (potential DoS) with an O(1) approach.

**Comment by davidmreed** [comment]
@prescod Would you mind re-approving?

**Review by prescod — APPROVED** [review]

**Pull request merged**
