### PR TITLE
Support deploying lwc subfolders

### PR DESCRIPTION
**Pull request by davisagli**
# Critical Changes

# Changes

# Issues Closed
- Fixed a bug where deploying an LWC component bundle using the `deploy` task did not include files in subfolders.

### CODE REVIEW

**Comment by davisagli** [comment]
@spelak-salesforce Does this make sense to you? Asking because this logic for filtering what we deploy from lwc folders originally came from you. I think the point was to avoid including __tests__ as well as files like eslint configuration or readmes, which I've attempted to preserve while adding support for actual component files in subfolders.

**Comment by spelak-salesforce** [comment]
@davisagli , [__mocks__](https://jestjs.io/docs/en/manual-mocks) is a valid subdirectory that's used by Jest where Jest automatically imports the mock in tests vs the production code.   

Maybe:
- Ignore all LWC subdirectories starting with/wrapped in `__`?
- The cci task has a configurable blocklist of LWC subdirectories to ignore?

```
lwc
|-- __mocks__ # lwc-jest automatically overrides
|             # imports matching paths in __mocks__.
|             # Useful for overriding @salesforce imports.
| 
|-- myComponent
|   |-- __tests__ # the usual suspect
|   |-- __mocks__ # technically could be here.
|
|-- ...   
```

**Comment by davisagli** [comment]
@spelak-salesforce Thanks, I like the idea of ignoring folders with `__`. I'll also check salesforce-alm to see what the CLI does.

**Comment by spelak-salesforce** [comment]
> @spelak-salesforce Thanks, I like the idea of ignoring folders with `__`. I'll also check salesforce-alm to see what the CLI does.

I don't think salesforce-alm does anything.  Devs always have to put these specific items in `.forceignore`.

**Comment by davisagli** [comment]
Oh wow, I'm surprised that has to be done manually. Does including the tests in the deployment lead to an error or is it just to avoid including unnecessary data?

Paying attention to .forceignore does sound like something that we should try to do.

**Comment by davisagli** [comment]
@spelak-salesforce actually I think items in .forceignore are probably already filtered out when converting sfdx format to mdapi format prior to deploying.

**Comment by spelak-salesforce** [comment]
> Oh wow, I'm surprised that has to be done manually. Does including the tests in the deployment lead to an error or is it just to avoid including unnecessary data?
> 
> Paying attention to .forceignore does sound like something that we should try to do.

Yes, we get sfdx deploy/push errors if we forget to add the items in the `.forceignore`.   Something like unexpected directories for `__tests__`/"can't find component..."; different error for `.eslintrc.json`.

**Comment by davisagli** [comment]
I think where this leaves us is:
1. This filtering is unnecessary for sfdx format because it gets filtered using .forceignore while converting
2. I'll make it skip any folder starting with `__` so that we handle `__mocks__` in mdapi format automatically.
3. We can look into supporting .forceignore for mdapi format but let's keep that as a separate user story.

**Review by davidmreed — APPROVED** [review]

**Pull request merged**
