### PR TITLE
Add better error handling for empty or invalid org and service env vars

### LINKED ISSUE #3340: Setting empty service environment variable throws unhelpful error
### Describe the bug

A specific error message that the environment variable is empty would be helpful in understanding this one.  This can impact anyone now that you don't have to set CUMULUSCI_KEYCHAIN_CLASS to have the keychain read env vars.

### Reproduction steps

```
$ export CUMULUSCI_SERVICE_github=
$ cci shell
Error: Expecting value: line 1 column 1 (char 0)
Run this command for more information about debugging errors: cci error --help
$ unset CUMULUSCI_SERVICE_github
$ cci shell
Python 3.10.2 (main, Apr 24 2022, 04:00:28) [Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>>
```

### Your CumulusCI and Python versions

CumulusCI version: 3.60.0
Python version: 3.10.2

### Operating System

OS X

### Windows environment

_No response_

### CumulusCI installation method

pipx

### Error Gist

_No response_

### Additional information

Traceback (most recent call last):
  File "/Users/jlantz/.local/pipx/venvs/cumulusci/lib/python3.10/site-packages/cumulusci/cli/cci.py", line 91, in main
    cli(args[1:], standalone_mode=False, obj=runtime)
  File "/Users/jlantz/.local/pipx/venvs/cumulusci/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jlantz/.local/pipx/venvs/cumulusci/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/jlantz/.local/pipx/venvs/cumulusci/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jlantz/.local/pipx/venvs/cumulusci/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jlantz/.local/pipx/venvs/cumulusci/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jlantz/.local/pipx/venvs/cumulusci/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/jlantz/.local/pipx/venvs/cumulusci/lib/python3.10/site-packages/cumulusci/cli/runtime.py", line 182, in new_func
    runtime._load_keychain()
  File "/Users/jlantz/.local/pipx/venvs/cumulusci/lib/python3.10/site-packages/cumulusci/core/runtime.py", line 95, in _load_keychain
    self.keychain = self.keychain_cls(self.project_config, keychain_key)
  File "/Users/jlantz/.local/pipx/venvs/cumulusci/lib/python3.10/site-packages/cumulusci/core/keychain/base_project_keychain.py", line 44, in __init__
    self._load_keychain()
  File "/Users/jlantz/.local/pipx/venvs/cumulusci/lib/python3.10/site-packages/cumulusci/core/keychain/base_project_keychain.py", line 50, in _load_keychain
    self._load_services()
  File "/Users/jlantz/.local/pipx/venvs/cumulusci/lib/python3.10/site-packages/cumulusci/core/keychain/encrypted_file_project_keychain.py", line 545, in _load_services
    self._load_services_from_environment()
  File "/Users/jlantz/.local/pipx/venvs/cumulusci/lib/python3.10/site-packages/cumulusci/core/keychain/encrypted_file_project_keychain.py", line 632, in _load_services_from_environment
    self._load_service_from_environment(env_var_name, value)
  File "/Users/jlantz/.local/pipx/venvs/cumulusci/lib/python3.10/site-packages/cumulusci/core/keychain/encrypted_file_project_keychain.py", line 637, in _load_service_from_environment
    service_config = ServiceConfig(json.loads(value))
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### PR DESCRIPTION
**Pull request by jlantz**
Adds extra error handling and a new exception, ServiceCannotBeLoaded, to match the exception already there for org load issues.  Should have 100% test coverage.

# Issues Closed
* Fixes #3340

### CODE REVIEW

**Comment by snorrissfdo** [comment]
[W-11720904](https://gus.lightning.force.com/a07EE000015vqGoYAI)

**Comment by jstvz** [comment]
No.

**Comment by jstvz** [comment]
Kidding, trying to reset the CLA bot.

**Comment by prescod** [comment]
Superceded by #3365 after a failed battle with github.

**Pull request closed without merging**
