### PR TITLE
[CCI] Ensure record types are included in retrieve profile task

### PR DESCRIPTION
**Pull request by jofsky**
# Critical Changes

# Changes

# Issues Closed

### CODE REVIEW

**Review by davisagli — COMMENTED** [review]
@jofsky Please write a pull request description before submitting for review. Is the point here to make sure that the record types listed in the record_types option are included in the retrieved profile?

**Comment by davisagli** [comment]
@jstvz Josh says this is from you...could you explain the context?

**Comment by jstvz** [comment]
@davisagli From d7ff367:

    Tasks can call ProfileGrantAllAccess with:
    
    ```yaml
    update_admin_profile:
        options:
            record_types:
                    - record_type: "{managed}Foo__c.{namespaced_org}Baz"
                      default: true
    ```
    
    If the referenced record type is not included in the default package.xml
    the task will throw an exception unless a custom package.xml is
    provided.
    
    Instead, this commit updates the class such that any record types are
    appended to the package.xml before retrieval.
    
    FIXME: This is tagged as a `[wip]` commit because this may not be the
    right way to handle namespace injection for these.

This was probably a little premature. I'll take a second pass and resubmit.

**Comment by davisagli** [comment]
@jstvz Thanks, I had not found that commit message. It seems pretty reasonable to me, though I am wondering what happens if there is an existing default record type that is not included in the retrieval.

**Pull request closed without merging**
