### PR TITLE
fix: escape stage name when running ensure_record_type task

### PR DESCRIPTION
**Pull request by leo-dcfa**
Fixed a bug we recently ran into while attempting to run `ensure_record_type` task against an org where there exists an Opportunity StageName with a ampesand.

### CODE REVIEW

**Review by jstvz — APPROVED** [review]
Thanks for the contribution, @leo-dcfa!

**Comment by leo-dcfa** [comment]
Glad I can contribute @jstvz

**Comment by leo-dcfa** [comment]
@jstvz just wanted to check, is this change scheduled for next release?

**Comment by jstvz** [comment]
> @jstvz just wanted to check, is this change scheduled for next release?

Yes.

**Pull request merged**
