### PR TITLE
LeadStatus picklist support

### PR DESCRIPTION
**Pull request by Br4nd0R**
# Changes
* Added support for LeadStatus value sets.

## Dev Notes
I noticed that the asserts on the actual error messages for a few of the tests were not being executed (the exception being raised prevented the line that was asserting the correct error message was present to not be reached). I went ahead and moved the error messages into constants in `value_sets.py` so that we now assert on the full error message that is thrown. Also was able to parameterize one of the existing tests and add a new test case.

### CODE REVIEW

**Comment by Br4nd0R** [comment]
@naicigam - I've included your changes in this branch and added tests for coverage. In order to merge this PR we will need you to sign a Contributor License Agreement. I'm working with @jlantz to get this to you as soon as possible. We appreciate your contribution greatly!

**Comment by Br4nd0R** [comment]
@naicigam - Can you go through [this form](https://cla.salesforce.com/sign-cla) and sign it. Once you reply back here confirming that you have completed the form we are all set to get this reviewed and merged.

**Review by davidmreed — APPROVED** [review]

**Comment by naicigam** [comment]
@Br4nd0R , I have singed the CLA.

**Comment by Br4nd0R** [comment]
For some reason it looks like GitHub [won't run GitHub actions when pull requests are generated from a forked repository](https://github.community/t/github-workflow-not-running-from-pull-request-from-forked-repository/16379).

I've gone ahead and created a new PR with the same content over at #2752

**Pull request closed without merging**
