### PR TITLE
Snowfakery 1.1

### PR DESCRIPTION
**Pull request by prescod**
Support Snowfakery 1.1:

https://github.com/SFDO-Tooling/Snowfakery/releases/tag/v1.1

### CODE REVIEW

**Comment by davisagli** [comment]
@prescod looks like you need to add version.txt to Snowfakery's manifest and make a new release

**Comment by prescod** [comment]
It's in there. Do you have a guess as to why it wouldn't be picked up?

https://github.com/SFDO-Tooling/Snowfakery/blob/master/MANIFEST.in

**Comment by prescod** [comment]
I guess MANIFEST.in is some kind of legacy file that's ignored by modern Pythons???

**Comment by davisagli** [comment]
@prescod I'm fairly sure that's not it. What commands are you using to make the release?

**Pull request closed without merging**
