### PR TITLE
Entry point for snowfakery

### PR DESCRIPTION
**Pull request by prescod**
# Changes

The `snowfakery` command is now available to CumulusCI users.

# Issues Closed

### CODE REVIEW

**Comment by davisagli** [comment]
This seems to already be the case:
- I created a new virtualenv, ran pip install cumulusci, and verified that there is a snowfakery script in the virtualenv's `bin`.
- When installing using homebrew, our formula links the snowfakery script here: https://github.com/SFDO-Tooling/homebrew-sfdo/blob/master/cumulusci.rb#L512

So, what is the scenario where it's not already working?

**Comment by davisagli** [comment]
Does this specifically make a different for pipx?

**Comment by prescod** [comment]
It seems that Windows users do not have access to the 'snowfakery' command so this is an attempt to fix that. I don't know for sure if it will work, to be honest, but seemed low-risk to try.

**Review by davisagli — APPROVED** [review]
It makes sense to me that that would be because of pipx, and that this would help.

**Pull request merged**
