### PR TITLE
use a github app instead of a personal access token to make releases of CumulusCI-Test

### PR DESCRIPTION
**Pull request by davisagli**
# Critical Changes

# Changes

# Issues Closed

### CODE REVIEW

**Review by prescod — APPROVED** [review]

**Comment by davisagli** [comment]
@prescod I'm still testing

**Comment by prescod** [comment]
So I should ignore review requests on this PR until you send one through a
different channel?

**Comment by davisagli** [comment]
@prescod no, I re-requested review because I'm ready now

**Comment by davisagli** [comment]
@prescod (sorry, I probably should have kept it as a draft initially)

**Review by prescod — APPROVED** [review]

**Pull request merged**
