### PR TITLE
Re-enable deprecated record type feature.

### PR DESCRIPTION
**Pull request by prescod**
The deprecated syntax for record types was accidentally broken when I was trying to make the deprecation warning conditional. This fixes the feature and adds a test so we don't break it again.

### CODE REVIEW

**Review by davidmreed — APPROVED** [review]

**Comment by davisagli** [comment]
@prescod please update the pull request description to include a release note in the usual format

**Comment by davisagli** [comment]
@prescod never mind, I see this is a fix for a change that wasn't released yet, so doesn't need its own release note

**Comment by prescod** [comment]
The change WAS released in 3.25

**Comment by davisagli** [comment]
@prescod oops, I was confused. Thanks for adding the note.

**Pull request merged**
