### PR TITLE
Remove lines that DG says are an anti-pattern and Python interpreter calls deprecated

### PR DESCRIPTION
**Pull request by prescod**
```
E   DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('cumulusci.core.tests')`.
E   Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
```

DG says:

> it creates a namespace package the setuptools way. it’s only important if there are actually any other distributions which add subpackages to those namespaces. My guess is that was probably only ever a theoretical idea about a way to make cumulusci pluggable; it’s probably an antipattern and should be removed after a quick search of github to confirm there aren’t any obvious dependencies on it 

I did not find any obvious dependencies and it isn't in our documentation as a supported extension point.

### CODE REVIEW

**Review by jstvz — COMMENTED** [review]
1. Do we need the `__init__.py` files at all? ([PEP 420](https://peps.python.org/pep-0420/))
2. There's one more in [`cumulusci/__init__.py`](https://github.com/SFDO-Tooling/CumulusCI/blob/cc6997e4786023fd7d2afb3460d03efe448ff2df/cumulusci/__init__.py#L8). Should we remove that one as well?

**Comment by prescod** [comment]
@jstvz Yeah I did try that but it didn't work and I didn't want to spend brain cells on fixing it.

```
____________ ERROR collecting cumulusci/core/tests/test_source.py ____________
ImportError while importing test module '/Users/pprescod/code/CumulusCI/cumulusci/core/tests/test_source.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
cumulusci/core/tests/test_source.py:24: in <module>
    from ..source import GitHubSource, LocalFolderSource
E   ImportError: attempted relative import with no known parent package
____________ ERROR collecting cumulusci/core/tests/test_utils.py _____________
ImportError while importing test module '/Users/pprescod/code/CumulusCI/cumulusci/core/tests/test_utils.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
cumulusci/core/tests/test_utils.py:11: in <module>
    from .. import utils
E   ImportError: attempted relative import with no known parent package
______ ERROR collecting cumulusci/salesforce_api/tests/test_metadata.py ______
ImportError while importing test module '/Users/pprescod/code/CumulusCI/cumulusci/salesforce_api/tests/test_metadata.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
E   ModuleNotFoundError: No module named 'tests.test_metadata'
__ ERROR collecting cumulusci/salesforce_api/tests/test_package_install.py ___
ImportError while importing test module '/Users/pprescod/code/CumulusCI/cumulusci/salesforce_api/tests/test_package_install.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
E   ModuleNotFoundError: No module named 'tests.test_package_install'
____ ERROR collecting cumulusci/salesforce_api/tests/test_package_zip.py _____
ImportError while importing test module '/Users/pprescod/code/CumulusCI/cumulusci/salesforce_api/tests/test_package_zip.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
E   ModuleNotFoundError: No module named 'tests.test_package_zip'
_______ ERROR collecting cumulusci/salesforce_api/tests/test_utils.py ________
ImportError while importing test module '/Users/pprescod/code/CumulusCI/cumulusci/salesforce_api/tests/test_utils.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
E   ModuleNotFoundError: No module named 'tests.test_utils'
```

**Comment by prescod** [comment]
@jstvz Okay I guess I'll just fix those errors instead of being lazy.

**Comment by prescod** [comment]
@jstvz  Nah...it opened a can of worms. I'll need to leave this for a future project.

**Pull request merged**
