### PR TITLE
Replace old resource links with update CumulusCI & Salesforce Robot

### PR DESCRIPTION
**Pull request by Julian88Tex**
# Critical Changes

# Changes
- Replaced old CumulusCI Keyword and Robot files with newer ones located further down in documentation

# Issues Closed

### CODE REVIEW

**Comment by davisagli** [comment]
@boakley Is there any reason to keep the old files here?

**Comment by boakley** [comment]
> @boakley Is there any reason to keep the old files here?

No, I don't think there's any reason to keep them around.

**Comment by davisagli** [comment]
@Julian88Tex Merging is blocked, because the builds didn't run due to this PR being submitted from a fork. I'll bypass that restriction to merge since it's a simple doc fix. But in the future please ask me for access to the repository so you can submit a PR from a feature/ branch inside the SFDO-Tooling/CumulusCI repo.

**Comment by Julian88Tex** [comment]
@davisagli Cool so I should just request temporary access? Is that how you would like others (non-SF employees) to also contribute?

**Comment by davisagli** [comment]
@Julian88Tex I can only add employees to the SFDO-Tooling org. For external contributions we need to have an employee review the branch, then copy it to an internal branch.

**Pull request merged**
