### PR TITLE
Fix returning cached preflight task results

### PR DESCRIPTION
**Pull request by davisagli**
@davidmreed This should fix the problem we saw with cached preflight task results. Do you see any easy way to improve the test so that we're actually testing for that?

# Critical Changes

# Changes

# Issues Closed

### CODE REVIEW

**Comment by davidmreed** [comment]
What about replicating the structure in V4S's installer that first triggered the bug? Two consecutive references to the same preflight check, with the first expected to pass based on the test configuration, and the second expected to fail? I think that could be asserted against based on how the test is laid out now.

**Comment by davisagli** [comment]
@davidmreed yeah, sounds good. I adjusted the test and confirmed that it only passes with the fix in place.

**Comment by davidmreed** [comment]
Looks like py27 is failing, but only on Windows.

**Comment by davisagli** [comment]
@davidmreed thanks for calling my attention to that. I added a sort to make sure the dict items end up in a stable order for the cache key.

**Pull request merged**
