### PR TITLE
Feature/project docs

### PR DESCRIPTION
**Pull request by jofsky**
# Critical Changes

# Changes

Creates a new command:`cci project doc` which creates an RST file documenting all the over-ridden cumulusci.yml tasks in that project. 

# Issues Closed

### CODE REVIEW

**Comment by davidmreed** [comment]
@jofsky  I think you accidentally branched off of a previous PR instead of `master` here. Rebase?

**Comment by jofsky** [comment]
@davidmreed fixed.

**Comment by davidmreed** [comment]
@jofsky I still see changes from your Release Notes branch here.

I think what you'll want to do is a [rebase-onto](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) (under "More Interesting Rebases" - that seems to describe this situation). That'll give you a clean branch off of `master` that you can force-push.

**Comment by jofsky** [comment]
Ah I see the issue.

**Pull request closed without merging**
